name: Plan and Apply Terraform changes
on:
  workflow_dispatch:
  push:
    branches:
      - main
      #- test - Showing that mulitple branches can be specified for an event as needed. 

  pull_request: 
    branches:
      - main
      #- test - Showing that mulitple branches can be specified for an event as needed. 

env:
  TERRAFORM_VERSION: 1.7.2
  TERRAGRUNT_VERSION: 0.56.0  
  TERRAFORM_WORKING_DIR: './applied/prod'

permissions:
  contents: write
  pull-requests: read
  issues: write

concurrency: createNewWorkFlow # ensures that only a single workflow in the same concurrency group will run at the same time.

jobs: 
  plan: 
    name: "Terragrunt Init, Validate and Plan"
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-24.04
    defaults:
      run: 
        working-directory: ${{env.TERRAFORM_WORKING_DIR}}
    steps: 
      - name: "Checkout"
        uses: actions/checkout@v4
        with: 
          ref: ${{github.event.pull_request.head.ref}} # ensures the branch that is downloaded to the runner is the one tied to pull request

      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: ${{env.TERRAFORM_VERSION}}
            terraform_wrapper: true

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
            terragrunt-version: ${{env.TERRAGRUNT_VERSION}}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name : Terragrunt init 
        id: init
        run: terragrunt run-all init -no-color --terragrunt-non-interactive  #no-color will ensure output has no color and will run automatically without showing use prompts

      - name: Terragrunt validate
        id: validate
        run: terragrunt run-all validate -no-color --terragrunt-non-interactive

      - name: Terragrunt plan
        id: plan
        run: terragrunt run-all plan -no-color --terragrunt-non-interactive
        continue-on-error: true

  apply: 
    name: "Terragrunt Apply"
    if: github.event_name == 'push'
    runs-on: ubuntu-24.04
    defaults:
      run: 
        working-directory: ${{env.TERRAFORM_WORKING_DIR}}
    steps: 
      - name: "Checkout"
        uses: actions/checkout@v4
        with: 
          ref: ${{github.event.pull_request.head.ref}}

      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: ${{env.TERRAFORM_VERSION}}
            terraform_wrapper: true

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
            terragrunt-version: ${{env.TERRAGRUNT_VERSION}}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      

      - name : Terragrunt init 
        id: init
        run: terragrunt run-all init -no-color --terragrunt-non-interactive  #will ensure output has no color and will run automatically without showng use prompts

      - name: Terragrunt Apply
        id: apply
        run: terragrunt run-all apply -no-color --terragrunt-non-interactive
        continue-on-error: true