# Run on call from another workflow

on:
    workflow_call:
      inputs:
        TERRAFORM_VERSION:
          description: "terraform version to be installed on runner"
          required: true
          type: string
        TERRAGRUNT_VERSION:
          description: "terragrunt version to be installed on runner"
          required: true
          type: string
        TERRAFORM_WORKING_DIR:
          description: "Path to the terraform config"
          required: true
          type: string
        AWS_REGION:
          required: true
          type: string
        ENVIRONMENT_NAME: 
          required: true
          type: string

jobs: 
  plan: 
    name: "Terragrunt Init, Apply"
    environment: ${{inputs.ENVIRONMENT_NAME}}
    runs-on: ubuntu-24.04
    defaults:
      run: 
        working-directory: ${{inputs.TERRAFORM_WORKING_DIR}}
    steps: 
      - name: "Checkout"
        uses: actions/checkout@v4
        with: 
          ref: ${{github.event.pull_request.head.ref}}
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{inputs.TERRAFORM_VERSION}}
          terraform_wrapper: true
  
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: ${{inputs.TERRAGRUNT_VERSION}}
  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{inputs.AWS_REGION}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  
      - name : Terragrunt init 
        id: init
        run: terragrunt run-all init -no-color --terragrunt-non-interactive  #will ensure output has no color and will run automatically without showng use prompts
  
      - name: Terragrunt Apply
        id: apply
        run: terragrunt run-all apply -no-color --terragrunt-non-interactive
        continue-on-error: true  
